print("hallo!! im your simple calculator, give me just two numbers then i shows addition, subtraction, multiplication, and division ")
input()
number1 = int(input("tell me the first number: "))
number2 = int(input("tell me the second number: "))
print("=" * 40)
print("-" * 3 , "addition: " , number1 + number2 , "-" * 3)
print("-" * 3 , "subtraction: " , number1 - number2 , "-" * 3)
print("-" * 3 , "multiplication: " , number1 * number2 , "-" * 3)
print("-" * 3 , " division: " , number1 / number2 , "-" * 3)
print("=" * 40)